//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the object_follow package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __object_follow__PIDPARAMCONFIG_H__
#define __object_follow__PIDPARAMCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace object_follow
{
  class pidParamConfigStatics;
  
  class pidParamConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(pidParamConfig &config, const pidParamConfig &max, const pidParamConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const pidParamConfig &config1, const pidParamConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, pidParamConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const pidParamConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pidParamConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const pidParamConfig &config) const = 0;
      virtual void getValue(const pidParamConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T pidParamConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (pidParamConfig::* field);

      virtual void clamp(pidParamConfig &config, const pidParamConfig &max, const pidParamConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const pidParamConfig &config1, const pidParamConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, pidParamConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const pidParamConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pidParamConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const pidParamConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const pidParamConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, pidParamConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, pidParamConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<pidParamConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(pidParamConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("enable_ekf_prediction"==(*_i)->name){enable_ekf_prediction = boost::any_cast<bool>(val);}
        if("enable_ekf_data_association"==(*_i)->name){enable_ekf_data_association = boost::any_cast<bool>(val);}
        if("enable_ekf_update"==(*_i)->name){enable_ekf_update = boost::any_cast<bool>(val);}
        if("init_sigma_location"==(*_i)->name){init_sigma_location = boost::any_cast<double>(val);}
        if("init_sigma_orientation"==(*_i)->name){init_sigma_orientation = boost::any_cast<double>(val);}
        if("motion_noise_0"==(*_i)->name){motion_noise_0 = boost::any_cast<double>(val);}
        if("motion_noise_1"==(*_i)->name){motion_noise_1 = boost::any_cast<double>(val);}
        if("motion_noise_2"==(*_i)->name){motion_noise_2 = boost::any_cast<double>(val);}
        if("motion_noise_3"==(*_i)->name){motion_noise_3 = boost::any_cast<double>(val);}
        if("hough_space_pixel_rho"==(*_i)->name){hough_space_pixel_rho = boost::any_cast<double>(val);}
        if("hough_space_pixel_theta"==(*_i)->name){hough_space_pixel_theta = boost::any_cast<double>(val);}
        if("hough_space_meter_rho"==(*_i)->name){hough_space_meter_rho = boost::any_cast<double>(val);}
        if("hough_space_line_threshold"==(*_i)->name){hough_space_line_threshold = boost::any_cast<double>(val);}
        if("line_sigma_rho"==(*_i)->name){line_sigma_rho = boost::any_cast<double>(val);}
        if("line_sigma_theta"==(*_i)->name){line_sigma_theta = boost::any_cast<double>(val);}
        if("enviroment_meter_width"==(*_i)->name){enviroment_meter_width = boost::any_cast<double>(val);}
        if("enviroment_meter_height"==(*_i)->name){enviroment_meter_height = boost::any_cast<double>(val);}
        if("map_pixel_width"==(*_i)->name){map_pixel_width = boost::any_cast<double>(val);}
        if("map_pixel_height"==(*_i)->name){map_pixel_height = boost::any_cast<double>(val);}
        if("map_meter_width"==(*_i)->name){map_meter_width = boost::any_cast<double>(val);}
        if("map_meter_height"==(*_i)->name){map_meter_height = boost::any_cast<double>(val);}
        if("robot_view_pixel_width"==(*_i)->name){robot_view_pixel_width = boost::any_cast<double>(val);}
        if("robot_view_pixel_height"==(*_i)->name){robot_view_pixel_height = boost::any_cast<double>(val);}
        if("robot_view_meter_width"==(*_i)->name){robot_view_meter_width = boost::any_cast<double>(val);}
        if("robot_view_meter_height"==(*_i)->name){robot_view_meter_height = boost::any_cast<double>(val);}
        if("robot_view_angle"==(*_i)->name){robot_view_angle = boost::any_cast<double>(val);}
      }
    }

    bool enable_ekf_prediction;
bool enable_ekf_data_association;
bool enable_ekf_update;
double init_sigma_location;
double init_sigma_orientation;
double motion_noise_0;
double motion_noise_1;
double motion_noise_2;
double motion_noise_3;
double hough_space_pixel_rho;
double hough_space_pixel_theta;
double hough_space_meter_rho;
double hough_space_line_threshold;
double line_sigma_rho;
double line_sigma_theta;
double enviroment_meter_width;
double enviroment_meter_height;
double map_pixel_width;
double map_pixel_height;
double map_meter_width;
double map_meter_height;
double robot_view_pixel_width;
double robot_view_pixel_height;
double robot_view_meter_width;
double robot_view_meter_height;
double robot_view_angle;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool enable_ekf_prediction;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool enable_ekf_data_association;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool enable_ekf_update;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double init_sigma_location;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double init_sigma_orientation;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double motion_noise_0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double motion_noise_1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double motion_noise_2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double motion_noise_3;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_space_pixel_rho;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_space_pixel_theta;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_space_meter_rho;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_space_line_threshold;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double line_sigma_rho;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double line_sigma_theta;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double enviroment_meter_width;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double enviroment_meter_height;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double map_pixel_width;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double map_pixel_height;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double map_meter_width;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double map_meter_height;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double robot_view_pixel_width;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double robot_view_pixel_height;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double robot_view_meter_width;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double robot_view_meter_height;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double robot_view_angle;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("pidParamConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const pidParamConfig &__max__ = __getMax__();
      const pidParamConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const pidParamConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const pidParamConfig &__getDefault__();
    static const pidParamConfig &__getMax__();
    static const pidParamConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const pidParamConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void pidParamConfig::ParamDescription<std::string>::clamp(pidParamConfig &config, const pidParamConfig &max, const pidParamConfig &min) const
  {
    return;
  }

  class pidParamConfigStatics
  {
    friend class pidParamConfig;
    
    pidParamConfigStatics()
    {
pidParamConfig::GroupDescription<pidParamConfig::DEFAULT, pidParamConfig> Default("Default", "", 0, 0, true, &pidParamConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.enable_ekf_prediction = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.enable_ekf_prediction = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.enable_ekf_prediction = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<bool>("enable_ekf_prediction", "bool", 0, "ekf_prediction", "", &pidParamConfig::enable_ekf_prediction)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<bool>("enable_ekf_prediction", "bool", 0, "ekf_prediction", "", &pidParamConfig::enable_ekf_prediction)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.enable_ekf_data_association = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.enable_ekf_data_association = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.enable_ekf_data_association = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<bool>("enable_ekf_data_association", "bool", 0, "ekf_data_association", "", &pidParamConfig::enable_ekf_data_association)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<bool>("enable_ekf_data_association", "bool", 0, "ekf_data_association", "", &pidParamConfig::enable_ekf_data_association)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.enable_ekf_update = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.enable_ekf_update = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.enable_ekf_update = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<bool>("enable_ekf_update", "bool", 0, "ekf_update", "", &pidParamConfig::enable_ekf_update)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<bool>("enable_ekf_update", "bool", 0, "ekf_update", "", &pidParamConfig::enable_ekf_update)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.init_sigma_location = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.init_sigma_location = 20.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.init_sigma_location = 5.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("init_sigma_location", "double", 0, "init_sigma_location", "", &pidParamConfig::init_sigma_location)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("init_sigma_location", "double", 0, "init_sigma_location", "", &pidParamConfig::init_sigma_location)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.init_sigma_orientation = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.init_sigma_orientation = 3.14;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.init_sigma_orientation = 0.39;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("init_sigma_orientation", "double", 0, "init_sigma_orientation", "", &pidParamConfig::init_sigma_orientation)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("init_sigma_orientation", "double", 0, "init_sigma_orientation", "", &pidParamConfig::init_sigma_orientation)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.motion_noise_0 = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.motion_noise_0 = 0.5;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.motion_noise_0 = 0.1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_0", "double", 0, "motion_noise 0", "", &pidParamConfig::motion_noise_0)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_0", "double", 0, "motion_noise 0", "", &pidParamConfig::motion_noise_0)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.motion_noise_1 = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.motion_noise_1 = 0.5;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.motion_noise_1 = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_1", "double", 0, "motion_noise 1", "", &pidParamConfig::motion_noise_1)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_1", "double", 0, "motion_noise 1", "", &pidParamConfig::motion_noise_1)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.motion_noise_2 = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.motion_noise_2 = 0.5;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.motion_noise_2 = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_2", "double", 0, "motion_noise 2", "", &pidParamConfig::motion_noise_2)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_2", "double", 0, "motion_noise 2", "", &pidParamConfig::motion_noise_2)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.motion_noise_3 = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.motion_noise_3 = 0.5;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.motion_noise_3 = 0.01;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_3", "double", 0, "motion_noise 3", "", &pidParamConfig::motion_noise_3)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("motion_noise_3", "double", 0, "motion_noise 3", "", &pidParamConfig::motion_noise_3)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_space_pixel_rho = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_space_pixel_rho = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_space_pixel_rho = 500.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_pixel_rho", "double", 0, "hough_space_size_rho", "", &pidParamConfig::hough_space_pixel_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_pixel_rho", "double", 0, "hough_space_size_rho", "", &pidParamConfig::hough_space_pixel_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_space_pixel_theta = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_space_pixel_theta = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_space_pixel_theta = 400.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_pixel_theta", "double", 0, "hough_space_size_theta", "", &pidParamConfig::hough_space_pixel_theta)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_pixel_theta", "double", 0, "hough_space_size_theta", "", &pidParamConfig::hough_space_pixel_theta)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_space_meter_rho = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_space_meter_rho = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_space_meter_rho = 5.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_meter_rho", "double", 0, "hough_space_resolution_rho", "", &pidParamConfig::hough_space_meter_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_meter_rho", "double", 0, "hough_space_resolution_rho", "", &pidParamConfig::hough_space_meter_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_space_line_threshold = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_space_line_threshold = 200.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_space_line_threshold = 30.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_line_threshold", "double", 0, "hough_space_line_threshold", "", &pidParamConfig::hough_space_line_threshold)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("hough_space_line_threshold", "double", 0, "hough_space_line_threshold", "", &pidParamConfig::hough_space_line_threshold)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.line_sigma_rho = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.line_sigma_rho = 200.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.line_sigma_rho = 0.5;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("line_sigma_rho", "double", 0, "line_sigma_rho", "", &pidParamConfig::line_sigma_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("line_sigma_rho", "double", 0, "line_sigma_rho", "", &pidParamConfig::line_sigma_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.line_sigma_theta = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.line_sigma_theta = 200.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.line_sigma_theta = 0.1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("line_sigma_theta", "double", 0, "line_sigma_theta", "", &pidParamConfig::line_sigma_theta)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("line_sigma_theta", "double", 0, "line_sigma_theta", "", &pidParamConfig::line_sigma_theta)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.enviroment_meter_width = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.enviroment_meter_width = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.enviroment_meter_width = 16.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("enviroment_meter_width", "double", 0, "enviroment_meter_width 0", "", &pidParamConfig::enviroment_meter_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("enviroment_meter_width", "double", 0, "enviroment_meter_width 0", "", &pidParamConfig::enviroment_meter_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.enviroment_meter_height = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.enviroment_meter_height = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.enviroment_meter_height = 16.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("enviroment_meter_height", "double", 0, "enviroment_meter_height 1", "", &pidParamConfig::enviroment_meter_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("enviroment_meter_height", "double", 0, "enviroment_meter_height 1", "", &pidParamConfig::enviroment_meter_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.map_pixel_width = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.map_pixel_width = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.map_pixel_width = 500.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_pixel_width", "double", 0, "map_pixel_width 2", "", &pidParamConfig::map_pixel_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_pixel_width", "double", 0, "map_pixel_width 2", "", &pidParamConfig::map_pixel_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.map_pixel_height = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.map_pixel_height = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.map_pixel_height = 500.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_pixel_height", "double", 0, "map_pixel_height 3", "", &pidParamConfig::map_pixel_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_pixel_height", "double", 0, "map_pixel_height 3", "", &pidParamConfig::map_pixel_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.map_meter_width = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.map_meter_width = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.map_meter_width = 18.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_meter_width", "double", 0, "map_meter_width 2", "", &pidParamConfig::map_meter_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_meter_width", "double", 0, "map_meter_width 2", "", &pidParamConfig::map_meter_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.map_meter_height = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.map_meter_height = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.map_meter_height = 18.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_meter_height", "double", 0, "map_meter_height 3", "", &pidParamConfig::map_meter_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("map_meter_height", "double", 0, "map_meter_height 3", "", &pidParamConfig::map_meter_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.robot_view_pixel_width = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.robot_view_pixel_width = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.robot_view_pixel_width = 500.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_pixel_width", "double", 0, "robot_view_pixel_width 2", "", &pidParamConfig::robot_view_pixel_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_pixel_width", "double", 0, "robot_view_pixel_width 2", "", &pidParamConfig::robot_view_pixel_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.robot_view_pixel_height = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.robot_view_pixel_height = 1000.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.robot_view_pixel_height = 500.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_pixel_height", "double", 0, "robot_view_pixel_height 3", "", &pidParamConfig::robot_view_pixel_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_pixel_height", "double", 0, "robot_view_pixel_height 3", "", &pidParamConfig::robot_view_pixel_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.robot_view_meter_width = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.robot_view_meter_width = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.robot_view_meter_width = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_meter_width", "double", 0, "robot_view_meter_width 2", "", &pidParamConfig::robot_view_meter_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_meter_width", "double", 0, "robot_view_meter_width 2", "", &pidParamConfig::robot_view_meter_width)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.robot_view_meter_height = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.robot_view_meter_height = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.robot_view_meter_height = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_meter_height", "double", 0, "robot_view_meter_height 3", "", &pidParamConfig::robot_view_meter_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_meter_height", "double", 0, "robot_view_meter_height 3", "", &pidParamConfig::robot_view_meter_height)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.robot_view_angle = -3.15;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.robot_view_angle = 3.15;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.robot_view_angle = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_angle", "double", 0, "robot_view_angle 3", "", &pidParamConfig::robot_view_angle)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(pidParamConfig::AbstractParamDescriptionConstPtr(new pidParamConfig::ParamDescription<double>("robot_view_angle", "double", 0, "robot_view_angle 3", "", &pidParamConfig::robot_view_angle)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(pidParamConfig::AbstractGroupDescriptionConstPtr(new pidParamConfig::GroupDescription<pidParamConfig::DEFAULT, pidParamConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<pidParamConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<pidParamConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<pidParamConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    pidParamConfig __max__;
    pidParamConfig __min__;
    pidParamConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const pidParamConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static pidParamConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &pidParamConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const pidParamConfig &pidParamConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const pidParamConfig &pidParamConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const pidParamConfig &pidParamConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<pidParamConfig::AbstractParamDescriptionConstPtr> &pidParamConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<pidParamConfig::AbstractGroupDescriptionConstPtr> &pidParamConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const pidParamConfigStatics *pidParamConfig::__get_statics__()
  {
    const static pidParamConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = pidParamConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PIDPARAMRECONFIGURATOR_H__
